name: wings_project
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  bloc: ^6.0.1
  flutter_bloc: ^6.0.1

  cupertino_icons: ^1.0.2
  tuple: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^0.1.3+1
  json_serializable: ^3.2.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/logos/
    - assets/images/ships/
    - xwing-data2/data/
    - xwing-data2/data/pilots/first-order/
    - xwing-data2/data/pilots/galactic-empire/
    - xwing-data2/data/pilots/galactic-republic/
    - xwing-data2/data/pilots/rebel-alliance/
    - xwing-data2/data/pilots/resistance/
    - xwing-data2/data/pilots/scum-and-villainy/
    - xwing-data2/data/pilots/separatist-alliance/
    
  fonts:
    - family: Coolveltica
      fonts:
        - asset: assets/fonts/coolveltica/coolvetica_rg.ttf